# This is a basic workflow that is manually triggered

name: DeployExersise 2

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch,push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: getcode
        uses: actions/checkout@V3
      - name: Install Dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Deply Code
        run: echo "Deploying"
